# faster builds on new travis setup not using sudo
sudo: false

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

services:
  - mysql

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer --version
  - travis_retry composer update --dev --prefer-dist --no-interaction
  # install php extensions
  - pear config-set preferred_state beta
  - printf "\n" | pecl install imagick
# setup application:

before_script:
  - mysql -e 'CREATE DATABASE yii2_app_ro;'
  - mysql -e 'CREATE DATABASE yii2_app_roa_test;'
  - composer deploy --  dbname=yii2_app_roa dbuser=root overwrite=1 dbpass= 

script:
  - composer run-tests
